--SAYFA SAYISI 300 DEN BUYUK EÞÝT OLANKÝTAPLAR--

--USE KutuphaneDb
--SELECT * FROM Kitaplar WHERE sayfasayisi>=300


--STOK ADEDÝ 90-113 ARASINDAKÝLERÝ LÝSTELEYELÝM
USE KutuphaneDb
--SELECT * FROM Kitaplar WHERE stok>=90 AND stok<=113

--SELECT * FROM KÝTAPLAR ORDER BY SAYFASAYÝSÝ DESC

SELECT * FROM Kitaplar ORDER BY turId,SAYFASAYÝSÝ DESC