// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjeDeneme_MVC_Efcore_CodeFirst.Models;

#nullable disable

namespace ProjeDeneme_MVC_Efcore_CodeFirst.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("ProjeDeneme_MVC_Efcore_CodeFirst.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rize",
                            ProductId = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kars",
                            ProductId = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Samsun",
                            ProductId = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "İstanbul",
                            ProductId = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ankara",
                            ProductId = 0
                        });
                });

            modelBuilder.Entity("ProjeDeneme_MVC_Efcore_CodeFirst.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ipone 13"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dell Xside"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Samsung A71"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Piranha X13"
                        });
                });

            modelBuilder.Entity("ProjeDeneme_MVC_Efcore_CodeFirst.Models.City", b =>
                {
                    b.HasOne("ProjeDeneme_MVC_Efcore_CodeFirst.Models.Product", null)
                        .WithOne("City")
                        .HasForeignKey("ProjeDeneme_MVC_Efcore_CodeFirst.Models.City", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjeDeneme_MVC_Efcore_CodeFirst.Models.Product", b =>
                {
                    b.Navigation("City");
                });
#pragma warning restore 612, 618
        }
    }
}
